seata:
   enabled: true
   application-id: client
   tx-service-group: test
   config:
      type: nacos
      nacos:
         namespace:
         serverAddr: 127.0.0.1:8848
         group: SEATA_GROUP
         username: "nacos"
         password: "nacos"
         data-id: seata.properties
   registry:
      type: nacos
      nacos:
         application: seata-server
         serverAddr: 127.0.0.1:8848
         group: SEATA_GROUP
         namespace:
         username: "nacos"
         password: "nacos"
server:
   tomcat:
      max-threads: 500